// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWyGk1s4J-Z3xluwm9gcoo_dtnhI5fhpo',
    appId: '1:9139867107:web:8983f24a8ed6558a8ba4d6',
    messagingSenderId: '9139867107',
    projectId: 'sportzones-1267b',
    authDomain: 'sportzones-1267b.firebaseapp.com',
    storageBucket: 'sportzones-1267b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo_n-3gHFc64MzGriyTuEhxym5-cAm_OE',
    appId: '1:9139867107:android:725d786310eddf5f8ba4d6',
    messagingSenderId: '9139867107',
    projectId: 'sportzones-1267b',
    storageBucket: 'sportzones-1267b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRgpFm_n3PbXOIu-a6mqUzqnwWLLYLaK4',
    appId: '1:9139867107:ios:993816fc81742a6c8ba4d6',
    messagingSenderId: '9139867107',
    projectId: 'sportzones-1267b',
    storageBucket: 'sportzones-1267b.firebasestorage.app',
    iosBundleId: 'com.example.sportzones',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRgpFm_n3PbXOIu-a6mqUzqnwWLLYLaK4',
    appId: '1:9139867107:ios:993816fc81742a6c8ba4d6',
    messagingSenderId: '9139867107',
    projectId: 'sportzones-1267b',
    storageBucket: 'sportzones-1267b.firebasestorage.app',
    iosBundleId: 'com.example.sportzones',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWyGk1s4J-Z3xluwm9gcoo_dtnhI5fhpo',
    appId: '1:9139867107:web:813836a4280d32e08ba4d6',
    messagingSenderId: '9139867107',
    projectId: 'sportzones-1267b',
    authDomain: 'sportzones-1267b.firebaseapp.com',
    storageBucket: 'sportzones-1267b.firebasestorage.app',
  );
}
